CityAccess/Controllers/AgreementsController.cs
using CityAccess.Controllers;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace CityAccess
{
    public class AgreementsController : Controller
    {
        private CityAccessEntities db = new CityAccessEntities();

        // GET: Agreements
        /// <summary>
        //  Querys de DB to present lis of agreements to a logged in user
        /// </summary>
        /// <param name="SearchString">to search by present words in agreement title</param>
        /// <param name="AgreementsService"></param>
        /// <param name="agr"></param>
        /// <param name="operator1">string to filter agreements by operator</param>
        /// <param name="agent">string to filter agreements by agent</param>
        /// <param name="partnerID">for external access through partner site</param>
        /// <returns>the view that displays a list of agreements on screen</returns>
        public ActionResult Index(string SearchString, string AgreementsService, bool? agr,  string operator1, string agent, int? partnerID)
        {
            //var agreements = db.Agreements.Include(a => a.commissionType1).Include(a => a.Partner).Include(a => a.Service);
            int? value = null;
            string baseService = "Base Service";

            IQueryable<CityAccess.Agr_Partn_Comm> queryable = null;
            var agreements = queryable;
            var agreements1 = queryable;

            var origin = false;

            // ViewBag.images = db.ServiceImages.Where(g => g.sequenceNR == 1).OrderBy(g =>g.Service.Agreements);

            if (Session["admin"] == null)
            {
                if (Session["userID"] == null && partnerID == null)
                {
                    return RedirectToAction("Index", "Login");
                }


                if (partnerID == null)
                {
                    partnerID = (int)Session["partnerID"];
                }
                else
                {
                    origin = true;
                }

                ViewBag.Services = (from ag in db.Agreements
                                    join serv in db.Services on ag.serviceID equals serv.ID
                                    where serv.operatorID == partnerID || ag.partnerID == null || ag.partnerID == partnerID
                                    select serv).Distinct();

                ViewBag.operators = (from ag in db.Agreements
                                     join serv in db.Services on ag.serviceID equals serv.ID
                                     join part in db.Partners on serv.operatorID equals part.ID
                                     where ag.partnerID == partnerID
                                     select part).Distinct();

                ViewBag.partners = (from ag in db.Agreements
                                    join serv in db.Services on ag.serviceID equals serv.ID
                                    join part in db.Partners on ag.partnerID equals part.ID
                                    where serv.operatorID == partnerID
                                    select part).Distinct();

                Partner partner = db.Partners.Where(x => x.ID == partnerID).First();

                if (partner.isAgent == true)
                {
                    ViewBag.isAgent = 1;
                }
                if (partner.isOperator == true)
                {
                    ViewBag.isOperator = 1;
                }


                //Reformular as querys a imagem dos servicesBooked e dos servicesRequested
                    if (partner.isAgent == true && partner.isOperator != true)
                    {
                        if (db.PartnerLogoes.Where(x => x.PartnerID == partnerID).Any())
                        {
                            agreements =
                                from ag in db.Agreements
                                join serv in db.Services on ag.serviceID equals serv.ID
                                join partn in db.Partners on serv.operatorID equals partn.ID
                                join servImg in db.ServiceImages on serv.ID equals servImg.serviceID
                                //join partLogo in db.PartnerLogoes on ag.partnerID equals partLogo.PartnerID
                                where servImg.sequenceNR == 1
                                where serv.isActive == true
                                where ag.partnerID == partnerID || (value == null ? ag.partnerID == null : ag.partnerID == value)

                                select new Agr_Partn_Comm { Agreement = ag, Partner = partn, BaseService = baseService, serviceImage = servImg/*, PartnerLogo = partLogo*/ };

                                 agreements1 =
                                        from ag in db.Agreements
                                        join serv in db.Services on ag.serviceID equals serv.ID
                                        join partn in db.Partners on serv.operatorID equals partn.ID
                                        where serv.isActive == true &&  (value == null ? serv.ServiceImages.FirstOrDefault().Image == null : serv.ServiceImages.FirstOrDefault().ID == value)
                                        where ag.partnerID == partnerID || (value == null ? ag.partnerID == null : ag.partnerID == value)

                                        select new Agr_Partn_Comm { Agreement = ag, Partner = partn, BaseService = baseService, serviceImage = null};

                                agreements = agreements.Union(agreements1);
                        }
                        else
                        {
                            agreements =
                                from ag in db.Agreements
                                join serv in db.Services on ag.serviceID equals serv.ID
                                join partn in db.Partners on serv.operatorID equals partn.ID
                                join servImg in db.ServiceImages on serv.ID equals servImg.serviceID
                                where servImg.sequenceNR == 1
                                where serv.isActive == true
                                where ag.partnerID == partnerID || (value == null ? ag.partnerID == null : ag.partnerID == value)

                                select new Agr_Partn_Comm {  Agreement = ag, Partner = partn, BaseService = baseService, serviceImage = servImg };

                            agreements1 =
                                        from ag in db.Agreements
                                        join serv in db.Services on ag.serviceID equals serv.ID
                                        join partn in db.Partners on serv.operatorID equals partn.ID
                                        where serv.isActive == true &&  (value == null ? serv.ServiceImages.FirstOrDefault().Image == null : serv.ServiceImages.FirstOrDefault().ID == value)
                                        where ag.partnerID == partnerID || (value == null ? ag.partnerID == null : ag.partnerID == value)

                                        select new Agr_Partn_Comm { Agreement = ag, Partner = partn, BaseService = baseService, serviceImage = null};

                                agreements = agreements.Union(agreements1);
                        }
                    }
                    else
                    {
                        if (partner.isAgent == true && partner.isOperator == true)
                        {
                            if (db.PartnerLogoes.Where(x => x.PartnerID == partnerID).Any())
                            {
                                agreements =
                                    from ag in db.Agreements
                                    join serv in db.Services on ag.serviceID equals serv.ID
                                    join partn in db.Partners on serv.operatorID equals partn.ID
                                    join servImg in db.ServiceImages on serv.ID equals servImg.serviceID
                                    //join partLogo in db.PartnerLogoes on ag.partnerID equals partLogo.PartnerID
                                    where servImg.sequenceNR == 1
                                    where serv.isActive == true
                                    where ag.partnerID == partnerID || (value == null ? ag.partnerID == null : ag.partnerID == value) || (serv.operatorID == partnerID && ag.partnerID != null && ag.partnerID != serv.operatorID)

                                    select new Agr_Partn_Comm { Agreement = ag, Partner = partn, BaseService = baseService, serviceImage = servImg, /*PartnerLogo = partLogo*/ };

                                agreements1 =
                                        from ag in db.Agreements
                                        join serv in db.Services on ag.serviceID equals serv.ID
                                        join partn in db.Partners on serv.operatorID equals partn.ID
                                        where serv.isActive == true &&  (value == null ? serv.ServiceImages.FirstOrDefault().Image == null : serv.ServiceImages.FirstOrDefault().ID == value)
                                        where ag.partnerID == partnerID || (value == null ? ag.partnerID == null : ag.partnerID == value) || (serv.operatorID == partnerID && ag.partnerID != null && ag.partnerID != serv.operatorID)

                                        select new Agr_Partn_Comm { Agreement = ag, Partner = partn, BaseService = baseService, serviceImage = null};

                                agreements = agreements.Union(agreements1);
                            }
                            else
                            {
                                agreements =
                                    from ag in db.Agreements

CityAccess/Controllers/MarketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CityAccess.Controllers
{
    public class MarketController : Controller
    {

        private CityAccessEntities db = new CityAccessEntities();

        // GET: Market
        public ActionResult Index(string searchFilter)
        {
            if (Session["admin"] == null)
            {
                if (Session["userID"] == null)
                {
                    return RedirectToAction("Index", "Login");
                }
            }

                var partners = db.Partners.Where(x => x.isOperator == true && x.isPublic == true && x.isTest != true);

                //if (!String.IsNullOrEmpty(TradeName))
                //{
                //    partners = partners.Where(s => s.tradeName == TradeName);
                //}

                if (!String.IsNullOrEmpty(searchFilter))
                {
                    partners = partners.Where(x => x.description.Contains(searchFilter) || x.tradeName.Contains(searchFilter));
                }


            return View(partners);
        }

        // GET: Market/Details/5
        public ActionResult Details(int id, string city)
        {
            if (Session["admin"] == null && Session["userID"] == null)
            {
                return RedirectToAction("Index", "Login");
            }


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var services = db.Services.Where(x => x.operatorID == id && x.isPublic == true);

            ViewBag.cities = (from serv in db.Services
                              join cities in db.Cities on serv.cityID equals cities.ID
                              where serv.operatorID == id
                              select cities).Distinct();

            Partner part = db.Partners.Where(x=> x.ID == id).First();
            ViewBag.operator1 = part.tradeName;

            if (!String.IsNullOrEmpty(city))
            {
               services = services.Where(x => x.City.name == city);
            }
            return View(services);
        }



    }
}

CityAccess/Views/Market/Details.cshtml
@model IEnumerable<CityAccess.Service>

@{
    /**/

    ViewBag.Title = "Details";
}

<div class="Header">
    <div class="Section-Title col-md-3">
        <h1>@ViewBag.operator1</h1>
    </div>
</div>


<div style="padding: 0px 40px 60px 40px; font-size: 12px" class="Content">

    <form asp-controller="Agreements" asp-action="Search" method="get" style="padding-left:0px;padding-bottom:10px;">
        <div class="search-wrapper">
            <div class="col-md-1" style="padding-bottom:9px;padding-top:8px;padding-right:3px;">
                <strong>Cities:</strong>
            </div>
            <div>
            @Html.DropDownList("city", new SelectList(ViewBag.cities, "name", "name"), "", htmlAttributes: new { @class = "no-padding form-horizontal col-md-1 col-sm-1", style = " width:120px; height: 30px;", onchange = "this.form.submit()" })
            </div>
            <div class="col-md-6 col-sm-offset-1">
               <strong> *For additional details, please contact the operator. To book please contact operator and establish an agreement.</strong>
            </div>
        </div>
    </form>


    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script>
        $(document).ready(function () {
            if ($(window).width() < 768) {
                $("#MainTable").removeClass("table");
                $("div").removeClass("table-wrapper");
                $(".logo").css('height', '50px');
            }
        });
    </script>

    <div class="table-wrapper">
        <table id="MainTable" class="table marketDet">
            <thead class="marketDet" role="rowgroup">
                <tr class="marketDet" role="row">
                    <th role="columnheader" class="marketDet">
                        Logo
                    </th>
                    <th role="columnheader" class="marketDet">
                        Service Name
                    </th>
                    <th role="columnheader" class="marketDet">
                        Price
                    </th>
                    <th role="columnheader" class="marketDet">
                        City
                    </th>
                    <th role="columnheader" class="marketDet">
                        Description
                    </th>
                </tr>
            </thead>


            @{
                var base64 = string.Empty;
                var imgSrc = string.Empty;
            }

            <tbody class="marketDet" role="rowgroup">
                @foreach (var item in Model)
                {
                    <tr class="marketDet" role="row">
                        <td role="gridcell" class="marketDet logo">

                            @if (item.ServiceImages.Where(x => x.sequenceNR == 1).FirstOrDefault() != null)
                            {
                                base64 = Convert.ToBase64String(item.ServiceImages.Where(x => x.sequenceNR == 1).First().Image);
                                imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                                <img src="@imgSrc" alt="IMAGES" style=" height:40px; width:80px" align="left" />
                            }
                            else
                            {
                                <span>-</span>
                            }
                        </td>
                        <td role="gridcell" class="marketDet">
                             @Html.DisplayFor(modelItem => item.name)
                        </td>
                        <td role="gridcell" class="marketDet" >
                        @if (item.price != null)
                        {
                            @Html.DisplayFor(modelItem => item.price)
                        }
                        else
                        {
                            <span>-</span>
                        }
                        </td>
                        <td role="gridcell" class="marketDet">
                                @Html.DisplayFor(modelItem => item.City.name)
                        </td>
                        <td role="gridcell" class="marketDet">
                                @Html.DisplayFor(modelItem => item.description)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

CityAccess/Views/Market/Index.cshtml
@model IEnumerable<CityAccess.Partner>

@{
    /**/

    ViewBag.Title = "Index";
}

<div class="Header">
    <div class="Section-Title col-md-6">
        <h1>Market</h1>
    </div>
</div>


<div style="padding: 0px 40px 60px 40px; font-size: 12px" class="Content">

    @*<form asp-controller="Agreements" asp-action="Search" method="get" style="padding-left:0px;padding-bottom:10px;">
        <div class="search-wrapper">

            @using (Html.BeginForm())
            {
            <div class="col-md-10" style="padding-right:5px;">
                <div id="filt2" class="text-search" style="float:left;">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    @Html.TextBox("searchFilter")
                </div>
                <input  type="submit" value="Search" />
            </div>
            }
        </div>
    </form>*@


    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script>
        $(document).ready(function () {
            if ($(window).width() < 768) {
                $("#MainTable").removeClass("table");
                $("div").removeClass("table-wrapper");
                $("#filt2").css('width', '100%');
                $(".logo").css('height', '60px');
            }
        });
    </script>

    <div class="table-wrapper">
        <table id="MainTable" class="table market">
            <thead class="market" role="rowgroup">
                <tr class="market" role="row">
                    <th role="columnheader" class="market">
                        
                    </th>
                    <th role="columnheader" class="market">
                        Trade name
                    </th>
                    <th role="columnheader" class="market">
                        Description
                    </th>
                    <th role="columnheader" class="market">
                        Contact e-mail
                    </th>
                    <th role="columnheader" class="market">
                        Contact phone
                    </th>
                </tr>
            </thead>


                    @{ 
                        var base64 = string.Empty;
                        var imgSrc = string.Empty;
                    }

            <tbody class="market" role="rowgroup">
                @foreach (var item in Model)
                {
                    <tr class="market" role="row">
                        <td id="logoTD" role="gridcell" class="market logo">

                            @if (item.PartnerLogoes.First().Image.Length > 0)
                            {
                            base64 = Convert.ToBase64String(item.PartnerLogoes.First().Image);
                            imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                            <img src="@imgSrc" alt="IMAGES" style=" height:50px; width:35px" align="left" />
                            }
                            else
                            {
                            <span>-</span>
                            }
                        </td>
                        <td role="gridcell" class="market">
                            <a href="@Url.Action("Details/"+item.ID, null, new { area = string.Empty, controller = "Market" }, Request.Url.Scheme)"> @Html.DisplayFor(modelItem => item.tradeName)</a>
                        </td>
                        <td role="gridcell" class="market">
                            @Html.DisplayFor(modelItem => item.description)
                        </td>
                        <td role="gridcell" class="market">
                            @if (item.ContactEmail != null)
                            {
                                @Html.DisplayFor(modelItem => item.ContactEmail)
                            }
                            else
                            {
                                <span>-</span>
                            }
                        </td>
                        <td role="gridcell" class="market">
                            @if (item.ContactPhone != null)
                            {
                                @Html.DisplayFor(modelItem => item.ContactPhone)
                            }
                            else
                            {
                                <span>-</span>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>