CityAccess/Controllers/PartnerSiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.IO;
using System.Web.Helpers;

using System.Web.Mvc.Html;
using System.Web.UI.WebControls;
using System.Web.UI;
using CityAccess.Controllers;
using System.Globalization;

namespace CityAccess.Controllers
{
    public class PartnerSiteController : Controller
    {

        private CityAccessEntities db = new CityAccessEntities();

        // GET: PartnerSite
        public ActionResult Index()
        {
            if (Session["admin"] == null)
            {
                if (Session["userID"] == null)
                {
                    return RedirectToAction("Index", "Login");
                }
            }

            return View();
        }


        //redirects to HeaderLinks tab View
        public ActionResult HeaderLinks()
        {

            if (Session["admin"] == null)
            {
                if (Session["userID"] == null)
                {
                    return RedirectToAction("Index", "Login");
                }
            }


            LinksPlus links = new CityAccess.LinksPlus();


            IQueryable<Link> queryable = null;
            var menuEntries = queryable;
            var partnerID = Session["partnerID"];

            var partnerSite = db.PartnerSites.Where(x => x.partnerID == (int)partnerID).FirstOrDefault();

            if (partnerSite != null)
            {
                menuEntries = db.Links.Where(a => a.partnerSiteID == partnerSite.ID).OrderBy(x => x.posHorizontal +" "+ x.posVertical).DefaultIfEmpty();
            }

            if(menuEntries.First() != null)
            {
                links.Links = menuEntries.ToList();
                var menusize = links.Links.Last().posHorizontal;
                ViewBag.MenuSize = menusize+1;
            }
            else
            {
                links.Links = new List<CityAccess.Link>();
                ViewBag.MenuSize = 0;
            }

            //links.Links.Add(new Link { value="abc", text ="abcd", posHorizontal=0, posVertical=0 });

            ViewBag.ListLength = links.Links.Count;

            for(int i = 0; i < links.Links.Count; i++)
            {
                links.Links[i].Index = i;
            }
            ViewBag.Tab = "abc";
            return View(links);
        }




        /// <summary>
        /// Saves PartnerSite menu 
        /// </summary>
        /// <param name="links">partner site menu links</param>
        /// <returns> Redirects to HeaderLinks view </returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult HeaderLinksPost(ICollection<Link> links)
        {
            if (Session["admin"] == null)
            {
                if (Session["userID"] == null)
                {
                    return RedirectToAction("Index", "Login");
                }
            }

            if (links != null)
            {
                var partnerID = Session["partnerID"];
                var partnerSite = db.PartnerSites.Where(x => x.partnerID == (int)partnerID).FirstOrDefault();

                if (partnerSite == null)     //Logo addition without having binary 
                {
                    partnerSite = new PartnerSite();

                    partnerSite.partnerID = (int)partnerID;

                    try
                    {
                        db.PartnerSites.Add(partnerSite);
                        db.SaveChanges();
                    }
                    catch (DbEntityValidationException dbEx)
                    {
                        String url = "PartnerSite/HeaderLinks";
                        int userID = (int)Session["userID"];

                        auxMethods.ErrorHandling(dbEx, url, userID);

                        return RedirectToAction("Index", "Error");
                    }
                }


                partnerSite = db.PartnerSites.Where(x => x.partnerID == (int)partnerID).First();

                foreach (var link in links)
                {
                    link.partnerSiteID = partnerSite.ID;

                    if (link.ID == 0)
                    {
                        db.Links.Add(link);
                    }
                    else
                    {
                        db.Entry(link).State = EntityState.Modified;
                    }
                }

                try
                {
                    db.SaveChanges();
                }
                catch (DbEntityValidationException dbEx)
                {
                    String url = "PartnerSite/HeaderLinks";
                    int userID = (int)Session["userID"];

                    auxMethods.ErrorHandling(dbEx, url, userID);

                    return RedirectToAction("Index", "Error");
                }
            }


            TempData["Tab"] = "links";
            return View("Index");
        }




        /// <summary>
        /// Delete a menu link 
        /// </summary>
        /// <param name="id">id of the link to be deleted</param>
        /// <returns> Redirects to HeaderLinks view </returns>
        [HttpPost]
        public Boolean DeleteLink(int? id)
        {
            if (Session["admin"] == null)
            {
                if (Session["userID"] == null)
                {
                    return false;
                }
            }


            try
            {
                Link link = db.Links.Find(id);

                if (link != null)
                {

                    if (link.IsDropMaster == true)
                    {
                        var links = db.Links.Where(x => x.posHorizontal == link.posHorizontal);

                        foreach (var lk in links)
                        {
                            db.Links.Remove(lk);
                        }
                    }
                    else
                    {
                        db.Links.Remove(link);
                    }
                    db.SaveChanges();
                }
            }

            catch (DbEntityValidationException dbEx)
            {

                String url = "PartnerSite/DeleteLink";
                int userID = (int)Session["userID"];
                auxMethods.ErrorHandling(dbEx, url, userID);

                return false;

            }
            return true;

        }


        //redirects to HomePageImg tab View
        public ActionResult HomePageImg()
        {
            if (Session["admin"] == null)
            {
                if (Session["userID"] == null)
                {
                    return RedirectToAction("Index", "Login");
                }
            }

            var bin = new CityAccess.BinaryPlus();
            var binar = new CityAccess.Binary();

            var partnerID = Session["partnerID"];

            var partnerSite = db.PartnerSites.Where(x => x.partnerID == (int)partnerID).FirstOrDefault();

            if (partnerSite != null)
            {
                binar = db.Binarys.Where(x => x.partnerSite_ID == partnerSite.ID && x.isBackground == true).FirstOrDefault();

                if (binar != null && binar.isBackground == true)
                {
                    bin.Binary1 = binar.Binary1;
                }
            }
            ViewBag.Tab = "abc";
            return View(bin);
        }

        //Saves partner site background image to the database

        //If no partnerSite created => creates new partnerSite and corresponding binary 
        //If no Binary exists => creates binary and associates it with corresponding partnerSite 
        //If Binary already exists => overrides the current binary
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BackgroundImg([Bind(Include="ID,Binary1,file,partnerSite_ID")]BinaryPlus binary)
        {

            if (Session["admin"] == null)
            {
                if (Session["userID"] == null)
                {
                    return RedirectToAction("Index", "Login");
                }
            }


            var partnerID = Session["partnerID"];

            var partnerSite = db.PartnerSites.Where(x => x.partnerID == (int)partnerID).FirstOrDefault();

            var bin = new CityAccess.Binary();

            if (binary.file != null)
            {
                bin.Binary1 = new WebImage(binary.file.InputStream).GetBytes();

                if (partnerSite == null)     //Logo addition without having binary 
                {
                    partnerSite = new PartnerSite();

                    partnerSite.partnerID = (int)partnerID;

                    db.PartnerSites.Add(partnerSite);
                    db.SaveChanges();

                    partnerSite = db.PartnerSites.Where(x => x.partnerID == (int)partnerID).FirstOrDefault();

                    bin.partnerSite_ID = partnerSite.ID;
                    bin.isBackground = true;


                    try
                    {
                        db.Binarys.Add(bin);
                        db.SaveChanges();
                    }
                    catch (DbEntityValidationException dbEx)
                    {
                        var url = "PartnerSite/BackgroundImg";
                        var userID = (int)Session["userID"];

                        auxMethods.ErrorHandling(dbEx, url, userID);
                    }
                }
                else
                {

                    Binary binar = db.Binarys.Where(a => a.partnerSite_ID == partnerSite.ID && a.isBackground == true).FirstOrDefault();

                    if (binar == null)
                    {
                        bin.partnerSite_ID = partnerSite.ID;
                        bin.isBackground = true;

                        try
                        {
                            db.Binarys.Add(bin);
                            db.SaveChanges();

CityAccess/Views/PartnerSite/Advanced.cshtml
@model CityAccess.PartnerSite
@{
    Layout = null;
}

@using (Html.BeginForm("AdvancedPost", "PartnerSite", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ID)
    <div class=" primaryDiv">
        <div class="form-group">
            <div class=" col-md-8 col-md-offset-2">
                @Html.Label("Partner site css")
            </div>
            <div class=" col-md-8 col-md-offset-2" style="padding-bottom:10px;">
                @Html.EditorFor(model => model.css, new { htmlAttributes = new { @class = "form-control partnerSite" } })
            </div>

            <div class="col-md-8 col-md-offset-2 ">
                <input type="submit" value="Save" class="btn btn-default" align="left"/>
            </div>
        </div>
    </div>
    <div class="secondaryDiv">
        <p style="padding-top:30vh;">To reset the css code to its original state submit your preferences in the style tab.<</p>
    </div>
}

CityAccess/Views/PartnerSite/BookingSuccessfull.cshtml
@model PartnerSiteElements
@{
    Layout = "~/Views/Shared/PartnerSiteLayout.cshtml";
}
    <div class="Content">
        <p>Booking successfull!</p>
    </div>

CityAccess/Views/PartnerSite/HeaderLinks.cshtml
@model LinksPlus
@{
    Layout = null;
}
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>

@using (Html.BeginForm("HeaderLinksPost", "PartnerSite", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="primaryDiv" id="primary">
        @Html.EditorFor(x => x.Links)
    </div>
    <div class="secondaryDiv">
        <div class="col-md-3 dropdown" style="margin-bottom: 7%;margin-top: 5%;">
            <button type="button" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-plus-sign"></span>
            </button>
            <div class="dropdown-content">
                <form>
                    <a onclick="addDropdown()" href="#">Dropdown</a>
                    <a onclick="addHorizontalField()" href="#">Button</a>
                </form>
            </div>
        </div>
        <div class="col-md-3" style="margin-bottom: 7%;margin-top: 5%;">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
}


    <script>

    var HorizontalLength = @ViewBag.MenuSize;
    var ListLength = @ViewBag.ListLength;
    var Drop_Pos = [];

    function addHorizontalField() {

        var html = "<div class='col-md-12 clearfix' id='Links_" + ListLength + "'>"
            + "<input data-val='true' data-val-number='The field posHorizontal must be a number.' data-val-required='The posHorizontal field is required.' id='Links_" + ListLength + "__posHorizontal' name='Links[" + ListLength + "].posHorizontal' type='hidden' value=" + HorizontalLength + ">"

            + "<input data-val='true' data-val-number='The field posVertical must be a number.' id='Links_" + ListLength + "__posVertical' name='Links[" + ListLength + "].posVertical' type='hidden' value='0'>"

            + "<div class='col-md-2' ><label for='Links_" + ListLength + "__Button_Url' class='control-label'>Button Url</label></div>"

            + " <div class='col-md-10' style='padding-bottom: 15px;'><input class='text-box single-line' id='Links_" + ListLength + "__value' name='Links[" + ListLength + "].value' type='text' value=''>"

            + "<span class='glyphicon glyphicon-remove' onclick='Remove(Links_" + ListLength + ", Links_" + ListLength + "__posHorizontal, Links_" + ListLength + "__posVertical, " + ListLength +")' data-html='true' style='padding-left: 4px; color:red;'></span></div>"

            + "<div class='col-md-2'><label for='Links_" + ListLength + "__Button_text' class='control-label'>Button text</label></div>"

            +"<div class='col-md-10' style='padding-bottom: 35px;'><input class='text-box single-line' id='Links_" + ListLength + "__text' name='Links[" + ListLength + "].text' type='text' value=''></div></div>";

        $("#primary").append(html);

        HorizontalLength+=1;
        ListLength+=1;
    }

    function addDropdown() {

        var html = "<div class='col-md-12 clearfix' id='Links_" + ListLength + "'>"
            + "<div id=" + HorizontalLength + "><input data-val='true' data-val-number='The field posHorizontal must be a number.' data-val-required='The posHorizontal field is required.' id='Links_" + ListLength + "__posHorizontal' name='Links[" + ListLength + "].posHorizontal' type='hidden' value=" + HorizontalLength + ">"

            + "<input data-val='true' data-val-number='The field posVertical must be a number.' id='Links_" + ListLength + "__posVertical' name='Links[" + ListLength + "].posVertical' type='hidden' value='0'>"

            + "<input id='Links_" + ListLength + "__IsDropMaster' name='Links[" + ListLength + "].IsDropMaster' type='hidden' value='true'>"

            + "<div class='col-md-2'><label for='Links_" + ListLength + "__Button_Url' class='control-label'>Button Url</label></div>"

            + "<div class='col-md-10' style='padding-bottom: 15px;'><input class='text-box single-line' id='Links_" + ListLength + "__value' name='Links[" + ListLength + "].value' type='text' value=''>"

            + "<span class='glyphicon glyphicon-remove' onclick='Remove(Links_" + ListLength + ", Links_" + ListLength + "__posHorizontal, Links_" + ListLength + "__posVertical, " + ListLength +")' data-html='true' style='padding-left: 4px; color:red;'></span></div>"

            + "<div class='col-md-2'><label for='Links_" + ListLength + "__Button_text' class='control-label'>Button text</label></div>"

            + "<div class='col-md-10' style='padding-bottom: 35px;'><input class='text-box single-line' id='Links_" + ListLength + "__text' name='Links[" + ListLength + "].text' type='text' value=''></div></div>";

        html = html + "<div class='col-md-9 col-md-offset-3 dropdown' style='margin-bottom: 5%;'><button type='button' class='btn btn-default btn-sm'><span class='glyphicon glyphicon-plus-sign' onclick='DropdownChild(" + HorizontalLength + ")'>Sub Field</span></button></div></div>";
        $("#primary").append(html);

        Drop_Pos[HorizontalLength] = 0;

        HorizontalLength+=1;
        ListLength+=1;
    }

    function DropdownChild(HorizontalPosition) {

        Drop_Pos[HorizontalPosition] += 1;

        var html = "<div class='col-md-12 clearfix' id='Links_" + ListLength + "'>"

            +"<input data-val='true' data-val-number='The field posHorizontal must be a number.' data-val-required='The posHorizontal field is required.' id='Links_" + ListLength + "__posHorizontal' name='Links[" + ListLength + "].posHorizontal' type='hidden' value=" + HorizontalPosition + ">"

            + "<input data-val='true' data-val-number='The field posVertical must be a number.' id='Links_" + ListLength + "__posVertical' name='Links[" + ListLength + "].posVertical' type='hidden' value=" + Drop_Pos[HorizontalPosition] + ">"

            + "<div class='col-md-offset-1 col-md-2'><label for='Links_" + ListLength + "__Button_Url' class='control-label'>Button Url</label></div>"

            + "<div class='col-md-9' style='padding-bottom: 15px;'><input class='text-box single-line' id='Links_" + ListLength + "__value' name='Links[" + ListLength + "].value' type='text' value=''>"

            + "<span class='glyphicon glyphicon-remove' onclick='Remove(Links_" + ListLength + ", Links_" + ListLength + "__posHorizontal, Links_" + ListLength + "__posVertical, "+ListLength+")' data-html='true' style='padding-left: 4px; color:red;'></span></div>"

            + "<div class='col-md-offset-1 col-md-2'><label for='Links_" + ListLength + "__Button_text' class='control-label'>Button text</label></div>"

            + "<div class='col-md-9' style='padding-bottom: 35px;'><input class='text-box single-line' id='Links_" + ListLength + "__text' name='Links[" + ListLength + "].text' type='text' value=''></div></div>";

        $("#" + HorizontalPosition + "").append(html);

        ListLength++;

    }


    function Remove(id, horz_el, vert_el, listIndex) {

        var vert_pos = $(vert_el).val();

        var horz_pos = $(horz_el).val();

        var horz_id;

        var drop_child;

        if (vert_pos == 0) {

            for (var i = 0; i < ListLength; i++) {

                horz_id = $("#Links_" + i + "__posHorizontal");

                if (horz_id.val() > horz_pos) {
                    horz_id.val(horz_id.val() - 1);
                }
            }
            Drop_Pos[horz_pos] == 0;
            HorizontalLength -= 1;

        } else {

            drop_child = $("#" + horz_pos);                

            for (var j = 0; j < ListLength; j++) {

                if (drop_child.find("#Links_" + j + "__posVertical").length) {

                    var child_verticalEl = drop_child.find("#Links_" + j + "__posVertical");

                    if (child_verticalEl.val() > vert_pos) {                    
                        child_verticalEl.val(child_verticalEl.val()-1)
                    }
                }
            }


            Drop_Pos[horz_pos] -= 1;
        }



        var mainDiv = $("#Links_" + listIndex);
        var idVal = mainDiv.find("#Links_" + listIndex + "__ID").val(); //maybe to specific for function purposes

        var result = confirm("Do you want to delete this entry?");
        if (result) {
            //Logic to delete the item

            $.post("/PartnerSite/DeleteLink", { id: idVal}, function (data) {
                //do whatever with the response
                //window.location.reload(false);
                return false;
            });
        }

        $(id).remove();

        }
    </script>

CityAccess/Views/PartnerSite/HomePageImg.cshtml
@model CityAccess.BinaryPlus
@{
    Layout = null;
}
@using (Html.BeginForm("BackgroundImg", "PartnerSite", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class=" primaryDiv">

        @{
            var base64 = string.Empty;
            var imgSrc = string.Empty;
            var hasImage = false;
            if (Model.Binary1 != null)
            {
                base64 = Convert.ToBase64String(Model.Binary1);
                imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                hasImage = true;
            }
        }
        <div class="form-group">
            @Html.HiddenFor(model => model.ID)
            @Html.HiddenFor(model => model.partnerSite_ID)
            <div class=" col-md-8 col-md-offset-2">
                @Html.Label("Current homepage image")
            </div>
            <div class=" col-md-8 col-md-offset-2" style="padding-bottom:10px;">
                @if (hasImage)
                {
                    <img src="@imgSrc" alt="IMAGES" style=" height:200px; width:400px" />
                }
                else
                {
                    <img src="~/Content/NoImage.png" style="height:160px;width:300px" />
                    <p>It appears you have not yet loaded your homepage image</p>
                }
            </div>
            <div class=" col-md-8 col-md-offset-2" style="padding-bottom:60px;">
                <label class=" btn btn-default btn-file">
                    Choose image
                    @Html.TextBoxFor(model => model.file, new { type = "file" })
                </label>
            </div>
            <div class="col-md-8 col-md-offset-2">
                <input type="submit" value="Save" class="btn btn-default" align="left" formenctype="multipart/form-data"/>
            </div>
        </div>
    </div>
    <div class="secondaryDiv">
        <p style="padding-top:30vh;">The maximum homepage image size is 2048 kb</p>
    </div>
}

CityAccess/Views/PartnerSite/Index.cshtml
<div class="tabsConfig">

    <!-- Nav tabs -->
    <ul id="tabstrip" class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active" id="homepage"><a href="#HomePageImg" aria-controls="first" role="tab" data-toggle="tab">Homepage Image</a></li>
        <li role="presentation" id="logo"><a href="#Logo" aria-controls="second" role="tab" data-toggle="tab">Logo</a></li>
        <li role="presentation" id="links"><a href="#HeaderLinks" aria-controls="third" role="tab" data-toggle="tab">Header Links</a></li>
        <li role="presentation" id="style"><a href="#Style" aria-controls="fourth" role="tab" data-toggle="tab">Style</a></li>
        <li role="presentation" id="advanced"><a href="#Advanced" aria-controls="fifth" role="tab" data-toggle="tab">Advanced</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="HomePageImg">

            @{
            if (TempData["Tab"] == null)
            {
                Html.RenderAction("HomePageImg");
            }
            }
        </div>
        <div role="tabpanel" class="tab-pane" id="Logo">

        </div>
        <div role="tabpanel" class="tab-pane active" id="HeaderLinks">

        </div>
        <div role="tabpanel" class="tab-pane" id="Style">

        </div>
        <div role="tabpanel" class="tab-pane" id="Advanced">

        </div>

    </div>

</div>

<script>

     var ReloadedTab = '@TempData["Tab"]';

      $(document).ready(function () {
        if (ReloadedTab.length)
        {
            $("#" + ReloadedTab + " a").trigger("click");
        }
      });

        $('#tabstrip a').click(function (e) {
        e.preventDefault()
        var tabID = $(this).attr("href").substr(1);
        $(".tab-pane").each(function () {
            console.log("clearing " + $(this).attr("id") + " tab");
            $(this).empty();
        });
       
        $.ajax({
            url: "/@ViewContext.RouteData.Values["controller"]/" + tabID,
            cache: false,
            type: "get",
            dataType: "html",
            success: function (result) {
                $("#" + tabID).html(result);
            }

        })
            $(this).tab('show');
});
</script>

CityAccess/Views/PartnerSite/Logo.cshtml
@model CityAccess.BinaryPlus
@{
    Layout = null;
}



@using (Html.BeginForm("LogoPost", "PartnerSite", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class=" primaryDiv">

        @{
            var base64 = string.Empty;
            var imgSrc = string.Empty;
            var hasImage = false;
            if (Model.Binary1 != null)
            {
                base64 = Convert.ToBase64String(Model.Binary1);
                imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                hasImage = true;
            }
        }
        <div class="form-group">
            <div class=" col-md-8 col-md-offset-2">
                @Html.Label("Current Logo")
            </div>
            <div class=" col-md-8 col-md-offset-2" style="padding-bottom:10px;">
                @if (hasImage)
                {
                    <img src="@imgSrc" alt="IMAGES" style=" height:35px; width:70px" />
                }
                else
                {
                    <img src="~/Content/NoImage.png" style="height:83px;width:100px" />
                    <p>It appears you have not yet loaded your logo</p>
                }
            </div>
            <div class=" col-md-8 col-md-offset-2" style="padding-bottom:30px;">
                <label class=" btn btn-default btn-file">
                    Choose Logo
                    @Html.TextBoxFor(model => model.file, new { type = "file", style = "display: none;" })
                </label>
            </div>

            <div class="col-md-8 col-md-offset-2">
                <input type="submit" value="Save" class="btn btn-default" align="left"  formenctype="multipart/form-data"/>
            </div>
        </div>
    </div>
    <div class="secondaryDiv">
        <p style="padding-top:30vh;">The maximum logo size is 2048 kb</p>
    </div>
}

CityAccess/Views/PartnerSite/PartnerAgreementPage.cshtml
@model PartnerSiteElements
@{
    Layout = "~/Views/Shared/PartnerSiteLayout.cshtml";
    //Layout = null;
}

@Html.Action("Index", "Agreements", new { partnerID = Model.PartnerID })

CityAccess/Views/PartnerSite/PartnerBookingPage.cshtml
@model PartnerSiteElements
@{
    Layout = "~/Views/Shared/PartnerSiteLayout.cshtml";
}

@Html.Action("Index", "Booking", new { agID = TempData["ag"] })

CityAccess/Views/PartnerSite/Style.cshtml
@model Style

@{
    Layout = null;
}

@using (Html.BeginForm("StylePost", "PartnerSite", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class=" primaryDiv">
        <div class="form-group">

            <div class=" col-md-8 col-md-offset-2" style="padding-bottom:10px;">
                @Html.Label("Menu Position")
            </div>
            <div class=" col-md-8 col-md-offset-2" style="padding-bottom:10px;">
                <div class="col-md-2">
                    Left
                </div>
                <div class=" col-md-10">
                    @Html.RadioButtonFor(model => model.MenuPosition, false)
                </div>
            </div>
            <div class=" col-md-8 col-md-offset-2" style="padding-bottom:60px;">
                <div class="col-md-2">
                    Right
                </div>
                <div class=" col-md-10">
                    @Html.RadioButtonFor(model => model.MenuPosition, true)
                </div>
            </div>

            <div class=" col-md-8 col-md-offset-2" style="padding-bottom:10px;">
                @Html.Label("Logo Position")
            </div>
            <div class=" col-md-8 col-md-offset-2" style="padding-bottom:10px;">
                <div class="col-md-2">
                    Left
                </div>
                <div class=" col-md-10">
                    @Html.RadioButtonFor(model => model.LogoPosition, false)
                </div>
            </div>
            <div class=" col-md-8 col-md-offset-2" style="padding-bottom:60px;">
                <div class="col-md-2">
                    Right
                </div>
                <div class=" col-md-10">
                    @Html.RadioButtonFor(model => model.LogoPosition, true)
                </div>
            </div>


            <div class=" col-md-8 col-md-offset-2" style="padding-bottom:10px;">
                <div class="col-md-2">
                    @Html.Label("Background Color")
                </div>
                <div class=" col-md-10">
                    @Html.EditorFor(model => model.BackgroundColor, new { htmlAttributes = new { @class = "form-control ", maxlength = "50" } })
                </div>
            </div>

            <div class=" col-md-8 col-md-offset-2" style="padding-bottom:10px;">
                <div class="col-md-2">
                    @Html.Label("Font")
                </div>
                <div class=" col-md-10">
                    @Html.DropDownListFor(model => model.Font, new SelectList(ViewBag.Fonts, "ID", "ID"), htmlAttributes: new { @class = "form-control", style = "width: 125px; height: 23px; font-size: 12px; align:left;" })
                    @Html.ValidationMessageFor(model => model.Font, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class=" col-md-8 col-md-offset-2" style="padding-bottom:10px;">
                <div class="col-md-2">
                    @Html.Label("Font Color")
                </div>
                <div class=" col-md-10">
                    @Html.EditorFor(model => model.FontColor, new { htmlAttributes = new { @class = "form-control ", maxlength = "50" } })
                </div>
            </div>

            <div class="col-md-8 col-md-offset-2">
                <input type="submit" value="Save" class="btn btn-default" align="left" />
            </div>
        </div>
    </div>
}